name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - main   # Trigger deployment on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout GitHub repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install --force

      # Step 4: Build the project (if you have a build step)
      - name: Build project
        run: npm run build --if-present

      # Step 5: Deploy to Azure App Service
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'MSLearnAppServiceHu'   # Replace with your Azure App Service name
          slot-name: 'production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
